mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml


spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/yifan?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 12344321
        slave:
          url: jdbc:oracle:thin:@100.10.101:1521:orcl
          driver-class-name: oracle.jdbc.driver.OracleDriver
          username: NCYY
          password: NCYY

#    url: jdbc:mysql://192.168.1.200/wyj?useUnicode=true&useSSL=false&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: wyj
#    password: wyj
#
#    ds1: #数据源1 MySQL
#      url: jdbc:mysql://localhost:3306/yifan?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 12344321
#    ds2: # 数据源2 Oracle
#      url: jdbc:oracle:thin:@10.100.10.44:1521:orcl
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      username: NCYY
#      password: NCYY

